import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/models/feed_post.dart';
import '../../domain/repositories/feed_repository.dart';
import '../utils/firestore_utils.dart';

class FirebaseFeedRepository implements FeedRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static const String _collection = 'feed';

  @override
  Future<List<FeedPost>> getFeedPosts({int limit = 10, dynamic lastDoc}) async {
    try {
      print('[FirebaseFeedRepository] Fetching feed posts...');
      Query query = _firestore
          .collection(_collection)
          .where('visibility', isEqualTo: 'public')
          .orderBy('timestamp', descending: true)
          .limit(limit);

      if (lastDoc != null && lastDoc is DocumentSnapshot) {
        query = query.startAfterDocument(lastDoc);
      }

      print('[FirebaseFeedRepository] Running query...');
      final snapshot = await query.get();
      print('[FirebaseFeedRepository] Received ${snapshot.docs.length} documents.');

      final posts = snapshot.docs.map((doc) {
        try {
          final data = mapFirestoreData(doc.data() as Map<String, dynamic>, doc.id);
          return FeedPost.fromJson(data);
        } catch (e) {
          print('[FirebaseFeedRepository] ERROR parsing document ${doc.id}: $e');
          return null;
        }
      }).whereType<FeedPost>().toList();

      print('[FirebaseFeedRepository] Successfully parsed ${posts.length} posts.');
      return posts;
    } catch (e, stack) {
      print('[FirebaseFeedRepository] CRITICAL ERROR: $e');
      print(stack);
      rethrow;
    }
  }

  @override
  Future<List<FeedPost>> getUserFeedPosts(String userId,
      {int limit = 10, dynamic lastDoc}) async {
    Query query = _firestore
        .collection(_collection)
        .where('userId', isEqualTo: userId)
        .orderBy('timestamp', descending: true)
        .limit(limit);

    if (lastDoc != null && lastDoc is DocumentSnapshot) {
      query = query.startAfterDocument(lastDoc);
    }

    final snapshot = await query.get();
    return snapshot.docs
        .map((doc) {
          try {
            final data = mapFirestoreData(doc.data() as Map<String, dynamic>, doc.id);
            return FeedPost.fromJson(data);
          } catch (e) {
            print('[FirebaseFeedRepository] ERROR parsing user post ${doc.id}: $e');
            return null;
          }
        })
        .whereType<FeedPost>()
        .toList();
  }

  @override
  Future<void> createFeedPost(FeedPost post) async {
    final data = post.toJson();
    data.remove('id'); // ID is generated by Firestore
    data['timestamp'] = DateTime.now().millisecondsSinceEpoch;
    await _firestore.collection(_collection).add(data);
  }

  @override
  Future<void> updateFeedPost(String postId, Map<String, dynamic> updates) async {
    await _firestore.collection(_collection).doc(postId).update(updates);
  }

  @override
  Future<void> deleteFeedPost(String postId) async {
    await _firestore.collection(_collection).doc(postId).delete();
  }

  @override
  Future<void> toggleLike(String postId, String userId) async {
    final docRef = _firestore.collection(_collection).doc(postId);
    final doc = await docRef.get();

    if (!doc.exists) return;

    final data = doc.data() as Map<String, dynamic>;
    final List<dynamic> likes = data['likes'] ?? [];

    if (likes.contains(userId)) {
      await docRef.update({
        'likes': FieldValue.arrayRemove([userId])
      });
    } else {
      await docRef.update({
        'likes': FieldValue.arrayUnion([userId])
      });
    }
  }

  @override
  Future<void> addComment(String postId, Map<String, dynamic> comment) async {
    await _firestore.collection(_collection).doc(postId).update({
      'comments': FieldValue.arrayUnion([
        {
          ...comment,
          'timestamp': DateTime.now().millisecondsSinceEpoch,
        }
      ])
    });
  }
}
