import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import '../../domain/models/comment.dart';
import '../../domain/models/feed_post.dart';
import '../../domain/repositories/feed_repository.dart';
import '../utils/firestore_utils.dart';
import '../../utils/map_utils.dart';

class FirebaseFeedRepository implements FeedRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static const String _collection = 'feed';
  static const int _maxBatchWrites = 450;

  @override
  Future<List<FeedPost>> getFeedPosts({int limit = 10, dynamic lastDoc}) async {
    try {
      debugPrint('[FirebaseFeedRepository] Fetching feed posts...');
      Query query = _firestore
          .collection(_collection)
          .where('visibility', isEqualTo: 'public')
          .where('userIsDeactivated', isNotEqualTo: true)
          .orderBy('userIsDeactivated')
          .orderBy('timestamp', descending: true)
          .limit(limit);

      if (lastDoc != null && lastDoc is DocumentSnapshot) {
        query = query.startAfterDocument(lastDoc);
      }

      debugPrint('[FirebaseFeedRepository] Running query...');
      final snapshot = await query.get();
      debugPrint(
        '[FirebaseFeedRepository] Received ${snapshot.docs.length} documents.',
      );

      final posts = snapshot.docs
          .map((doc) {
            try {
              final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
              return FeedPost.fromJson(data);
            } catch (e) {
              debugPrint(
                '[FirebaseFeedRepository] ERROR parsing document ${doc.id}: $e',
              );
              return null;
            }
          })
          .whereType<FeedPost>()
          .toList();

      debugPrint(
        '[FirebaseFeedRepository] Successfully parsed ${posts.length} posts.',
      );
      return posts;
    } catch (e, stack) {
      debugPrint('[FirebaseFeedRepository] CRITICAL ERROR: $e');
      debugPrint(stack.toString());
      rethrow;
    }
  }

  @override
  Future<List<FeedPost>> getFollowingFeed(
    List<String> followedUserIds, {
    int limit = 10,
    dynamic lastDoc,
  }) async {
    if (followedUserIds.isEmpty) return [];

    try {
      final chunks = [];
      for (var i = 0; i < followedUserIds.length; i += 10) {
        chunks.add(
          followedUserIds.sublist(
            i,
            i + 10 > followedUserIds.length ? followedUserIds.length : i + 10,
          ),
        );
      }

      final List<FeedPost> allPosts = [];

      for (final chunk in chunks) {
        Query query = _firestore
            .collection(_collection)
            .where('userId', whereIn: chunk)
            .where('userIsDeactivated', isNotEqualTo: true)
            .orderBy('userIsDeactivated')
            .orderBy('timestamp', descending: true)
            .limit(limit);

        if (lastDoc != null && lastDoc is DocumentSnapshot) {
          query = query.startAfterDocument(lastDoc);
        }

        final snapshot = await query.get();
        allPosts.addAll(
          snapshot.docs.map((doc) {
            final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
            return FeedPost.fromJson(data);
          }).toList(),
        );
      }

      allPosts.sort((a, b) => b.timestamp.compareTo(a.timestamp));
      if (allPosts.length > limit) {
        return allPosts.sublist(0, limit);
      }
      return allPosts;
    } catch (e) {
      debugPrint('[FirebaseFeedRepository] Error fetching following feed: $e');
      rethrow;
    }
  }

  @override
  Future<List<FeedPost>> getUserFeedPosts(
    String userId, {
    int limit = 10,
    dynamic lastDoc,
  }) async {
    Query query = _firestore
        .collection(_collection)
        .where('userId', isEqualTo: userId)
        .orderBy('timestamp', descending: true)
        .limit(limit);

    if (lastDoc != null && lastDoc is DocumentSnapshot) {
      query = query.startAfterDocument(lastDoc);
    }

    final snapshot = await query.get();
    return snapshot.docs
        .map((doc) {
          try {
            final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
            return FeedPost.fromJson(data);
          } catch (e) {
            debugPrint(
              '[FirebaseFeedRepository] ERROR parsing user post ${doc.id}: $e',
            );
            return null;
          }
        })
        .whereType<FeedPost>()
        .toList();
  }

  @override
  Future<void> createFeedPost(FeedPost post) async {
    final data = post.toJson();
    data.remove('id'); // ID is generated by Firestore
    data['timestamp'] = DateTime.now().millisecondsSinceEpoch;
    await _firestore.collection(_collection).add(data);
  }

  @override
  Future<void> updateFeedPost(
    String postId,
    Map<String, dynamic> updates,
  ) async {
    await _firestore.collection(_collection).doc(postId).update(updates);
  }

  @override
  Future<void> deleteFeedPost(String postId) async {
    final batches = <WriteBatch>[];
    var batch = _firestore.batch();
    var writeCount = 0;

    void queueDelete(DocumentReference<Map<String, dynamic>> reference) {
      if (writeCount >= _maxBatchWrites) {
        batches.add(batch);
        batch = _firestore.batch();
        writeCount = 0;
      }
      batch.delete(reference);
      writeCount++;
    }

    queueDelete(_firestore.collection(_collection).doc(postId));

    final comments = await _firestore
        .collection('comments')
        .where('feedPostId', isEqualTo: postId)
        .get();
    for (final comment in comments.docs) {
      queueDelete(comment.reference);
    }

    if (writeCount > 0) batches.add(batch);
    for (final batch in batches) {
      await batch.commit();
    }
  }

  @override
  Future<void> toggleLike(String postId, String userId) async {
    final docRef = _firestore.collection(_collection).doc(postId);
    final doc = await docRef.get();

    if (!doc.exists) return;

    final data = asStringMap(doc.data());
    final List<dynamic> likes = data['likes'] ?? [];

    if (likes.contains(userId)) {
      await docRef.update({
        'likes': FieldValue.arrayRemove([userId]),
      });
    } else {
      await docRef.update({
        'likes': FieldValue.arrayUnion([userId]),
      });
    }
  }

  @override
  Future<void> addComment(String postId, Map<String, dynamic> comment) async {
    final postRef = _firestore.collection(_collection).doc(postId);
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final commentRef = _firestore.collection('comments').doc();

    final postSnapshot = await postRef.get();
    if (!postSnapshot.exists) {
      throw StateError('Post not found');
    }

    await commentRef.set({
      ...comment,
      'feedPostId': postId,
      'timestamp': timestamp,
      'likes': const <String>[],
      'replies': const <Map<String, dynamic>>[],
    });

    try {
      await postRef.update({'commentCount': FieldValue.increment(1)});
    } catch (error) {
      debugPrint(
        '[FirebaseFeedRepository] Comment saved but count update failed: $error',
      );
    }
  }

  @override
  Future<void> addCommentReply(
    String postId,
    String commentId,
    CommentReply reply,
  ) async {
    if (await _addTopLevelCommentReply(commentId, reply)) return;

    final postRef = _firestore.collection(_collection).doc(postId);
    final replyId =
        reply.id ?? '${DateTime.now().millisecondsSinceEpoch}_${reply.userId}';
    final replyData = reply
        .copyWith(id: replyId, likes: reply.likes ?? const [])
        .toJson();

    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) {
        throw StateError('Post not found');
      }

      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      var changed = false;

      final updated = comments.map((raw) {
        if (raw is! Map) return raw;
        final comment = Map<String, dynamic>.from(raw);
        final id = comment['id']?.toString();
        if (id != commentId) return raw;

        final replies = List<dynamic>.from(comment['replies'] ?? const []);
        comment['replies'] = [...replies, replyData];
        changed = true;
        return comment;
      }).toList();

      if (changed) {
        transaction.update(postRef, {'comments': updated});
      }
    });
  }

  @override
  Future<void> updateCommentText(
    String postId,
    String commentId,
    String text,
  ) async {
    if (await _updateTopLevelCommentText(commentId, text)) return;

    final postRef = _firestore.collection(_collection).doc(postId);
    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) return;
      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      var changed = false;
      final updated = comments.map((raw) {
        if (raw is! Map) return raw;
        final comment = Map<String, dynamic>.from(raw);
        if (comment['id']?.toString() != commentId) return raw;
        comment['text'] = text;
        comment['updatedAt'] = DateTime.now().millisecondsSinceEpoch;
        changed = true;
        return comment;
      }).toList();
      if (changed) transaction.update(postRef, {'comments': updated});
    });
  }

  @override
  Future<void> deleteComment(String postId, String commentId) async {
    if (await _deleteTopLevelComment(postId, commentId)) return;

    final postRef = _firestore.collection(_collection).doc(postId);
    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) return;
      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      final updated = comments.where((raw) {
        if (raw is! Map) return true;
        return raw['id']?.toString() != commentId;
      }).toList();
      if (updated.length != comments.length) {
        transaction.update(postRef, {'comments': updated});
      }
    });
  }

  @override
  Future<void> updateReplyText(
    String postId,
    String commentId,
    String replyId,
    String text,
  ) async {
    if (await _updateTopLevelReplyText(commentId, replyId, text)) return;

    final postRef = _firestore.collection(_collection).doc(postId);
    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) return;
      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      var changed = false;
      final updated = comments.map((raw) {
        if (raw is! Map) return raw;
        final comment = Map<String, dynamic>.from(raw);
        if (comment['id']?.toString() != commentId) return raw;
        final replies = List<dynamic>.from(comment['replies'] ?? const []);
        comment['replies'] = replies.map((replyRaw) {
          if (replyRaw is! Map) return replyRaw;
          final reply = Map<String, dynamic>.from(replyRaw);
          final id = reply['id']?.toString();
          final timestamp = reply['timestamp']?.toString();
          if (id != replyId && timestamp != replyId) return replyRaw;
          reply['text'] = text;
          reply['updatedAt'] = DateTime.now().millisecondsSinceEpoch;
          changed = true;
          return reply;
        }).toList();
        return comment;
      }).toList();
      if (changed) transaction.update(postRef, {'comments': updated});
    });
  }

  @override
  Future<void> deleteReply(
    String postId,
    String commentId,
    String replyId,
  ) async {
    if (await _deleteTopLevelReply(commentId, replyId)) return;

    final postRef = _firestore.collection(_collection).doc(postId);
    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) return;
      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      var changed = false;
      final updated = comments.map((raw) {
        if (raw is! Map) return raw;
        final comment = Map<String, dynamic>.from(raw);
        if (comment['id']?.toString() != commentId) return raw;
        final replies = List<dynamic>.from(comment['replies'] ?? const []);
        final filtered = replies.where((replyRaw) {
          if (replyRaw is! Map) return true;
          final id = replyRaw['id']?.toString();
          final timestamp = replyRaw['timestamp']?.toString();
          return id != replyId && timestamp != replyId;
        }).toList();
        if (filtered.length != replies.length) {
          comment['replies'] = filtered;
          changed = true;
        }
        return comment;
      }).toList();
      if (changed) transaction.update(postRef, {'comments': updated});
    });
  }

  @override
  Future<void> toggleCommentLike(
    String postId,
    String commentId,
    String userId,
  ) async {
    if (await _toggleTopLevelCommentLike(commentId, userId)) return;

    final postRef = _firestore.collection(_collection).doc(postId);
    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) return;
      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      var changed = false;
      final updated = comments.map((raw) {
        if (raw is! Map) return raw;
        final comment = Map<String, dynamic>.from(raw);
        if (comment['id']?.toString() != commentId) return raw;
        final likes = List<dynamic>.from(comment['likes'] ?? const []);
        if (likes.contains(userId)) {
          likes.removeWhere((id) => id == userId);
        } else {
          likes.add(userId);
        }
        comment['likes'] = likes;
        changed = true;
        return comment;
      }).toList();
      if (changed) transaction.update(postRef, {'comments': updated});
    });
  }

  @override
  Future<void> toggleReplyLike(
    String postId,
    String commentId,
    String replyId,
    String userId,
  ) async {
    if (await _toggleTopLevelReplyLike(commentId, replyId, userId)) return;

    final postRef = _firestore.collection(_collection).doc(postId);
    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) return;
      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      var changed = false;
      final updated = comments.map((raw) {
        if (raw is! Map) return raw;
        final comment = Map<String, dynamic>.from(raw);
        if (comment['id']?.toString() != commentId) return raw;
        final replies = List<dynamic>.from(comment['replies'] ?? const []);
        comment['replies'] = replies.map((replyRaw) {
          if (replyRaw is! Map) return replyRaw;
          final reply = Map<String, dynamic>.from(replyRaw);
          final id = reply['id']?.toString();
          final timestamp = reply['timestamp']?.toString();
          if (id != replyId && timestamp != replyId) return replyRaw;
          final likes = List<dynamic>.from(reply['likes'] ?? const []);
          if (likes.contains(userId)) {
            likes.removeWhere((id) => id == userId);
          } else {
            likes.add(userId);
          }
          reply['likes'] = likes;
          changed = true;
          return reply;
        }).toList();
        return comment;
      }).toList();
      if (changed) transaction.update(postRef, {'comments': updated});
    });
  }

  @override
  Future<String> uploadPostImage(Uint8List bytes, String fileName) async {
    final storageRef = FirebaseStorage.instance
        .ref()
        .child('feed_images')
        .child('${DateTime.now().millisecondsSinceEpoch}_$fileName');

    final uploadTask = await storageRef.putData(
      bytes,
      SettableMetadata(contentType: 'image/jpeg'),
    );

    return await uploadTask.ref.getDownloadURL();
  }

  @override
  Future<FeedPost?> getFeedPost(String postId) async {
    try {
      final doc = await _firestore.collection(_collection).doc(postId).get();
      if (!doc.exists) return null;
      final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
      return FeedPost.fromJson(data);
    } catch (e) {
      debugPrint(
        '[FirebaseFeedRepository] Error fetching single post $postId: $e',
      );
      return null;
    }
  }

  Future<bool> _addTopLevelCommentReply(
    String commentId,
    CommentReply reply,
  ) async {
    final commentRef = _firestore.collection('comments').doc(commentId);
    final replyId =
        reply.id ?? '${DateTime.now().millisecondsSinceEpoch}_${reply.userId}';
    final replyData = reply
        .copyWith(id: replyId, likes: reply.likes ?? const [])
        .toJson();

    return _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(commentRef);
      if (!snap.exists) return false;
      transaction.update(commentRef, {
        'replies': FieldValue.arrayUnion([replyData]),
      });
      return true;
    });
  }

  Future<bool> _updateTopLevelCommentText(String commentId, String text) async {
    final commentRef = _firestore.collection('comments').doc(commentId);
    return _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(commentRef);
      if (!snap.exists) return false;
      transaction.update(commentRef, {
        'text': text,
        'updatedAt': DateTime.now().millisecondsSinceEpoch,
      });
      return true;
    });
  }

  Future<bool> _deleteTopLevelComment(String postId, String commentId) async {
    final commentRef = _firestore.collection('comments').doc(commentId);
    final postRef = _firestore.collection(_collection).doc(postId);
    final snap = await commentRef.get();
    if (!snap.exists) return false;
    await commentRef.delete();
    try {
      await postRef.update({'commentCount': FieldValue.increment(-1)});
    } catch (error) {
      debugPrint(
        '[FirebaseFeedRepository] Comment deleted but count update failed: $error',
      );
    }
    return true;
  }

  Future<bool> _updateTopLevelReplyText(
    String commentId,
    String replyId,
    String text,
  ) async {
    return _updateTopLevelReplies(commentId, (reply) {
      final id = reply['id']?.toString();
      final timestamp = reply['timestamp']?.toString();
      if (id != replyId && timestamp != replyId) return false;
      reply['text'] = text;
      reply['updatedAt'] = DateTime.now().millisecondsSinceEpoch;
      return true;
    });
  }

  Future<bool> _deleteTopLevelReply(String commentId, String replyId) async {
    final commentRef = _firestore.collection('comments').doc(commentId);
    return _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(commentRef);
      if (!snap.exists) return false;
      final data = snap.data() ?? {};
      final replies = List<dynamic>.from(data['replies'] ?? const []);
      final updated = replies.where((replyRaw) {
        if (replyRaw is! Map) return true;
        final id = replyRaw['id']?.toString();
        final timestamp = replyRaw['timestamp']?.toString();
        return id != replyId && timestamp != replyId;
      }).toList();
      if (updated.length != replies.length) {
        transaction.update(commentRef, {'replies': updated});
      }
      return true;
    });
  }

  Future<bool> _toggleTopLevelCommentLike(
    String commentId,
    String userId,
  ) async {
    final commentRef = _firestore.collection('comments').doc(commentId);
    return _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(commentRef);
      if (!snap.exists) return false;
      final data = snap.data() ?? {};
      final likes = List<dynamic>.from(data['likes'] ?? const []);
      transaction.update(commentRef, {
        'likes': likes.contains(userId)
            ? FieldValue.arrayRemove([userId])
            : FieldValue.arrayUnion([userId]),
      });
      return true;
    });
  }

  Future<bool> _toggleTopLevelReplyLike(
    String commentId,
    String replyId,
    String userId,
  ) async {
    return _updateTopLevelReplies(commentId, (reply) {
      final id = reply['id']?.toString();
      final timestamp = reply['timestamp']?.toString();
      if (id != replyId && timestamp != replyId) return false;

      final likes = List<dynamic>.from(reply['likes'] ?? const []);
      if (likes.contains(userId)) {
        likes.removeWhere((id) => id == userId);
      } else {
        likes.add(userId);
      }
      reply['likes'] = likes;
      return true;
    });
  }

  Future<bool> _updateTopLevelReplies(
    String commentId,
    bool Function(Map<String, dynamic> reply) updateReply,
  ) async {
    final commentRef = _firestore.collection('comments').doc(commentId);
    return _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(commentRef);
      if (!snap.exists) return false;
      final data = snap.data() ?? {};
      final replies = List<dynamic>.from(data['replies'] ?? const []);
      var changed = false;
      final updated = replies.map((replyRaw) {
        if (replyRaw is! Map) return replyRaw;
        final reply = Map<String, dynamic>.from(replyRaw);
        if (!updateReply(reply)) return replyRaw;
        changed = true;
        return reply;
      }).toList();
      if (changed) transaction.update(commentRef, {'replies': updated});
      return true;
    });
  }
}
