import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import '../../domain/models/comment.dart';
import '../../domain/models/feed_post.dart';
import '../../domain/repositories/feed_repository.dart';
import '../utils/firestore_utils.dart';
import '../../utils/map_utils.dart';

class FirebaseFeedRepository implements FeedRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static const String _collection = 'feed';

  @override
  Future<List<FeedPost>> getFeedPosts({int limit = 10, dynamic lastDoc}) async {
    try {
      debugPrint('[FirebaseFeedRepository] Fetching feed posts...');
      Query query = _firestore
          .collection(_collection)
          .where('visibility', isEqualTo: 'public')
          .where('userIsDeactivated', isNotEqualTo: true)
          .orderBy('userIsDeactivated')
          .orderBy('timestamp', descending: true)
          .limit(limit);

      if (lastDoc != null && lastDoc is DocumentSnapshot) {
        query = query.startAfterDocument(lastDoc);
      }

      debugPrint('[FirebaseFeedRepository] Running query...');
      final snapshot = await query.get();
      debugPrint(
        '[FirebaseFeedRepository] Received ${snapshot.docs.length} documents.',
      );

      final posts = snapshot.docs
          .map((doc) {
            try {
              final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
              return FeedPost.fromJson(data);
            } catch (e) {
              debugPrint(
                '[FirebaseFeedRepository] ERROR parsing document ${doc.id}: $e',
              );
              return null;
            }
          })
          .whereType<FeedPost>()
          .toList();

      debugPrint(
        '[FirebaseFeedRepository] Successfully parsed ${posts.length} posts.',
      );
      return posts;
    } catch (e, stack) {
      debugPrint('[FirebaseFeedRepository] CRITICAL ERROR: $e');
      debugPrint(stack.toString());
      rethrow;
    }
  }

  @override
  Future<List<FeedPost>> getFollowingFeed(
    List<String> followedUserIds, {
    int limit = 10,
    dynamic lastDoc,
  }) async {
    if (followedUserIds.isEmpty) return [];

    try {
      final chunks = [];
      for (var i = 0; i < followedUserIds.length; i += 10) {
        chunks.add(
          followedUserIds.sublist(
            i,
            i + 10 > followedUserIds.length ? followedUserIds.length : i + 10,
          ),
        );
      }

      final List<FeedPost> allPosts = [];

      for (final chunk in chunks) {
        Query query = _firestore
            .collection(_collection)
            .where('userId', whereIn: chunk)
            .where('userIsDeactivated', isNotEqualTo: true)
            .orderBy('userIsDeactivated')
            .orderBy('timestamp', descending: true)
            .limit(limit);

        if (lastDoc != null && lastDoc is DocumentSnapshot) {
          query = query.startAfterDocument(lastDoc);
        }

        final snapshot = await query.get();
        allPosts.addAll(
          snapshot.docs.map((doc) {
            final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
            return FeedPost.fromJson(data);
          }).toList(),
        );
      }

      allPosts.sort((a, b) => b.timestamp.compareTo(a.timestamp));
      if (allPosts.length > limit) {
        return allPosts.sublist(0, limit);
      }
      return allPosts;
    } catch (e) {
      debugPrint('[FirebaseFeedRepository] Error fetching following feed: $e');
      rethrow;
    }
  }

  @override
  Future<List<FeedPost>> getUserFeedPosts(
    String userId, {
    int limit = 10,
    dynamic lastDoc,
  }) async {
    Query query = _firestore
        .collection(_collection)
        .where('userId', isEqualTo: userId)
        .orderBy('timestamp', descending: true)
        .limit(limit);

    if (lastDoc != null && lastDoc is DocumentSnapshot) {
      query = query.startAfterDocument(lastDoc);
    }

    final snapshot = await query.get();
    return snapshot.docs
        .map((doc) {
          try {
            final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
            return FeedPost.fromJson(data);
          } catch (e) {
            debugPrint(
              '[FirebaseFeedRepository] ERROR parsing user post ${doc.id}: $e',
            );
            return null;
          }
        })
        .whereType<FeedPost>()
        .toList();
  }

  @override
  Future<void> createFeedPost(FeedPost post) async {
    final data = post.toJson();
    data.remove('id'); // ID is generated by Firestore
    data['timestamp'] = DateTime.now().millisecondsSinceEpoch;
    await _firestore.collection(_collection).add(data);
  }

  @override
  Future<void> updateFeedPost(
    String postId,
    Map<String, dynamic> updates,
  ) async {
    await _firestore.collection(_collection).doc(postId).update(updates);
  }

  @override
  Future<void> deleteFeedPost(String postId) async {
    final batch = _firestore.batch();
    batch.delete(_firestore.collection(_collection).doc(postId));

    final comments = await _firestore
        .collection('comments')
        .where('feedPostId', isEqualTo: postId)
        .get();
    for (final comment in comments.docs) {
      batch.delete(comment.reference);
    }

    await batch.commit();
  }

  @override
  Future<void> toggleLike(String postId, String userId) async {
    final docRef = _firestore.collection(_collection).doc(postId);
    final doc = await docRef.get();

    if (!doc.exists) return;

    final data = asStringMap(doc.data());
    final List<dynamic> likes = data['likes'] ?? [];

    if (likes.contains(userId)) {
      await docRef.update({
        'likes': FieldValue.arrayRemove([userId]),
      });
    } else {
      await docRef.update({
        'likes': FieldValue.arrayUnion([userId]),
      });
    }
  }

  @override
  Future<void> addComment(String postId, Map<String, dynamic> comment) async {
    final postRef = _firestore.collection(_collection).doc(postId);
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final commentId = '${timestamp}_${comment['userId']}';

    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) {
        throw StateError('Post not found');
      }

      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      final embeddedComment = <String, dynamic>{
        ...comment,
        'id': commentId,
        'timestamp': timestamp,
      };

      transaction.update(postRef, {
        'comments': [...comments, embeddedComment],
      });
    });
  }

  @override
  Future<void> addCommentReply(
    String postId,
    String commentId,
    CommentReply reply,
  ) async {
    final postRef = _firestore.collection(_collection).doc(postId);
    final replyId =
        reply.id ?? '${DateTime.now().millisecondsSinceEpoch}_${reply.userId}';
    final replyData = reply
        .copyWith(id: replyId, likes: reply.likes ?? const [])
        .toJson();

    await _firestore.runTransaction((transaction) async {
      final snap = await transaction.get(postRef);
      if (!snap.exists) {
        throw StateError('Post not found');
      }

      final data = asStringMap(snap.data());
      final comments = List<dynamic>.from(data['comments'] ?? const []);
      var changed = false;

      final updated = comments.map((raw) {
        if (raw is! Map) return raw;
        final comment = Map<String, dynamic>.from(raw);
        final id = comment['id']?.toString();
        if (id != commentId) return raw;

        final replies = List<dynamic>.from(comment['replies'] ?? const []);
        comment['replies'] = [...replies, replyData];
        changed = true;
        return comment;
      }).toList();

      if (changed) {
        transaction.update(postRef, {'comments': updated});
      }
    });
  }

  @override
  Future<String> uploadPostImage(Uint8List bytes, String fileName) async {
    final storageRef = FirebaseStorage.instance
        .ref()
        .child('feed_images')
        .child('${DateTime.now().millisecondsSinceEpoch}_$fileName');

    final uploadTask = await storageRef.putData(
      bytes,
      SettableMetadata(contentType: 'image/jpeg'),
    );

    return await uploadTask.ref.getDownloadURL();
  }

  @override
  Future<FeedPost?> getFeedPost(String postId) async {
    try {
      final doc = await _firestore.collection(_collection).doc(postId).get();
      if (!doc.exists) return null;
      final data = mapFirestoreData(asStringMap(doc.data()), doc.id);
      return FeedPost.fromJson(data);
    } catch (e) {
      debugPrint(
        '[FirebaseFeedRepository] Error fetching single post $postId: $e',
      );
      return null;
    }
  }
}
