// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkiPyC3xawvqek2ZUJPhLIupLKwRwW4t0',
    appId: '1:601247128838:web:1bd0d3f4e026297d025287',
    messagingSenderId: '601247128838',
    projectId: 'studio-8109133561-1eb90',
    authDomain: 'studio-8109133561-1eb90.firebaseapp.com',
    storageBucket: 'studio-8109133561-1eb90.firebasestorage.app',
    measurementId: 'G-HN4J52XZMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsm9w_Hkac6sXgBqweqSU_wYjfp4i19dM',
    appId: '1:601247128838:android:52362145c242e23c025287',
    messagingSenderId: '601247128838',
    projectId: 'studio-8109133561-1eb90',
    storageBucket: 'studio-8109133561-1eb90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-K5JtaISPaJ2dmcSRLlTwOZDylhM4Kc',
    appId: '1:601247128838:ios:893b6e08739de61e025287',
    messagingSenderId: '601247128838',
    projectId: 'studio-8109133561-1eb90',
    storageBucket: 'studio-8109133561-1eb90.firebasestorage.app',
    androidClientId: '601247128838-qkfo2gp0e7icjr441mginpute3tm69ug.apps.googleusercontent.com',
    iosClientId: '601247128838-dks8dmicdnb04t4isqbqr0s8cgp7m7p5.apps.googleusercontent.com',
    iosBundleId: 'in.wreadom.librebookFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-K5JtaISPaJ2dmcSRLlTwOZDylhM4Kc',
    appId: '1:601247128838:ios:893b6e08739de61e025287',
    messagingSenderId: '601247128838',
    projectId: 'studio-8109133561-1eb90',
    storageBucket: 'studio-8109133561-1eb90.firebasestorage.app',
    androidClientId: '601247128838-qkfo2gp0e7icjr441mginpute3tm69ug.apps.googleusercontent.com',
    iosClientId: '601247128838-dks8dmicdnb04t4isqbqr0s8cgp7m7p5.apps.googleusercontent.com',
    iosBundleId: 'in.wreadom.librebookFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOgMpxNGS3sJ6Rnoh2m1l_kwjQPSOu_aw',
    appId: '1:601247128838:web:ab6e74e35064f216025287',
    messagingSenderId: '601247128838',
    projectId: 'studio-8109133561-1eb90',
    authDomain: 'studio-8109133561-1eb90.firebaseapp.com',
    storageBucket: 'studio-8109133561-1eb90.firebasestorage.app',
    measurementId: 'G-1VZNP1KDKD',
  );

}